name: hive_app
description: La aplicación definitiva para encontrar eventos y hacer amigos.

version: 2.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.3
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  intl: ^0.18.1
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  camera: ^0.10.5+4
  flutter_secure_storage: ^5.0.2
  flutter_local_notifications: ^12.0.3
  geolocator: ^10.1.0
  timer_builder: ^2.0.0
  firebase_core: ^1.10.0
  firebase_crashlytics: ^2.9.0
  firebase_performance: ^0.7.0+9
  pull_to_refresh: ^2.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Regular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          style: normal
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic

    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-Regular.ttf
          style: normal
        - asset: assets/fonts/Jost-Bold.ttf
          weight: 400
         
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          style: normal
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
